[IN]
INV1=https://in-dev.ttgroup-dev.com/hall
#INV5=https://in-u5.ttgroup-dev.com/hall 已暫停
INV6=https://in-u6.ttgroup-dev.com/hall #.vip更改com
INPV6=https://7ind.com/hall #正式環境

[DS]
WEB=https://advantplay.com/
gitlab=https://gitlab.diresoft.net/default/tournament.git



